name: Tencent Cloud COS Action
on: [push]
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install coscmd
        run: sudo pip install coscmd

      - name: Configure coscmd
        env:
          secret_id: ${{secrets.SECRET_ID}}
          secret_key: ${{secrets.SECRET_KEY}}
          bucket: ${{secrets.BUCKET}}
          region: ap-beijing
          run: coscmd config -a $secret_id -s $secret_key -b $bucket -r $region
          
      - name: Upload to COS
        run: coscmd upload -rs --delete -f ./ / --ignore "./.git/*"
