name: Tencent Cloud COS Action

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install coscmd
        run: sudo pip install -U coscmd

      - name: Configure coscmd
        env:
          secret_id: ${{secrets.SECRETID}}
          secret_key: ${{secrets.SECRETKEY}}
          bucket: ${{secrets.BUCKET}}
          region: ap-beijing
          run: coscmd config -a $SECRETID -s $SECRETKEY -b $BUCKET -r $REGION
          
      - name: Upload to COS
        run: coscmd upload -r ./ / --ignore "./.git/*"
