name: Tencent Cloud COS Action

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
 
      - name: Install coscmd
        run: pip install -U coscmd

      - name: Configure coscmd
        env:
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-beijing
          run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
          
      - name: Upload to COS
        run: coscmd upload -r ./ / --ignore "./.git/*"
