name: Tencent Cloud COS Action
on: 
  push:
    branches:
      - master
jobs:
  cos-action:
    runs-on: ubuntu-latest
    steps:
    - name: upload
      uses: xynm/cos-action@v2
      with:
        COMMAND: coscmd upload -rs --skipmd5 / / --ignore ".git/*"
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
