- name:zyli.top
  uses:zyli.top/master@v1
  with:
    secret_id:AKIDub5Vo6Wesz5jgWCUR97rY1EHdy52OPvI
    secret_key:Z4kLjzQhx686VdZLxNXSAcqoaDbmhM6b
    cos_bucket:abc-dh-1251151891
    cos_region:abc-dh-1251151891
    local_path:/
    remote_path:/
    clean: # optional
