- name:zyli.top
  uses:zyli.top/master@v1
  with:
    secret_id:${{ secrets.SECRET_ID }}
    secret_key:${{ secrets.SECRET_KEY }}
    cos_bucket:${{ secrets.BUCKET }}
    cos_region:ap-beijing
    local_path:/
    remote_path:/
    clean: # optional
